name: 🧬 Nova Análise de Primers
description: Submeta seus primers para validação in silico no pipeline
title: "[Análise] - "
labels: ["analise-pendente"]
body:
  - type: markdown
    attributes:
      value: |
        ### Bem-vindo ao Pipeline de Validação de Primers!
        Preencha os campos abaixo com os parâmetros para a sua simulação de PCR.

  - type: input
    id: nome
    attributes:
      label: Nome do Pesquisador
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: E-mail para Notificação
      placeholder: "Ex: email@exemplo.com"
    validations:
      required: true

  - type: input
    id: primer_fwd
    attributes:
      label: "Primer Forward (5' -> 3')"
      placeholder: "Ex: CCAGCASCYGCGGTAATTCC"
    validations:
      required: true

  - type: input
    id: primer_rev
    attributes:
      label: "Primer Reverse (5' -> 3')"
      placeholder: "Ex: RCCACAAGCYARTTATCC"
    validations:
      required: true

  - type: dropdown
    id: regiao_alvo
    attributes:
      label: Região Alvo
      options:
        - "16S"
        - "18S"
        - "ITS"
        - "Outra"
    validations:
      required: true

  - type: dropdown
    id: banco_dados
    attributes:
      label: Tipo de organismo
      options:
        - "Protozoa"
        - "Fungi"
    validations:
      required: true

  - type: input
    id: max_mismatches
    attributes:
      label: "Máximo de Mismatches (Extremidade 3')"
      placeholder: "Valores de 0 a 5"
    validations:
      required: true

  - type: input
    id: amp_min
    attributes:
      label: Tamanho Mínimo do Amplicon (bp)
    validations:
      required: true

  - type: input
    id: amp_max
    attributes:
      label: Tamanho Máximo do Amplicon (bp)
    validations:
      required: true

  - type: input
    id: tm_min
    attributes:
      label: Temperatura de Melting mínima (Tm)
      value: "0"
    validations:
      required: true

  - type: input
    id: evalue
    attributes:
      label: E-value Máximo
    validations:
      required: true

  - type: input
    id: cobertura
    attributes:
      label: Cobertura mínima (%)
      placeholder: "De 0 a 100"
    validations:
      required: true

  - type: input
    id: max_hits
    attributes:
      label: Limite de hits
    validations:
      required: true
